---
title: "Example 9: Two arm | Fixed design | Binary"
format: html
---

```{r setup}
devtools::load_all("../rxsim/")
```

## Scenario
Capture scenario parameters. We will assume piece-wise linear enrollment.

```{r scenario}
sample_size <- 100
arms <- c("pbo", "trt")
allocation <- c(1,1)
enrollment_fn <- function(n) rexp(n, rate = 1)
dropout_fn <- function(n) rexp(n, rate = 0.01)
scenario <- tidyr::expand_grid(
  sample_size = sample_size,
  allocation = list(allocation)
)
```

## Populations
Define population generators.

```{r population}
population_generators <- list(
  pbo = function(n) data.frame(
    id = 1:n,
    value = rbinom(n, size = 1, prob = 0.1),
    readout_time = 1
  ),
  trt = function(n) data.frame(
    id = 1:n,
    value = rbinom(n, size = 1, prob = 0.18),
    readout_time = 1
  )
)
```

## Triggers & Analysis
We want to do a t-test when 100 subjects have been enrolled.

```{r trigger}
analysis_generators <- list(
  final = list(
    trigger = rlang::exprs(
      sum(!is.na(enroll_time)) >= !!sample_size
    ),
    analysis = function(df, timer){
      df_enrolled <- df |> subset(!is.na(enroll_time))
      
      logreg <- glm(value ~ arm, data = df_enrolled, family = "binomial") #logistic regression
      odds_ratio <- exp(coef(logreg)["armtrt"])
      logreg_p <- summary(logreg)$coefficients["armtrt", "Pr(>|z|)"]/2
      logreg_p <- ifelse(odds_ratio > 1, logreg_p, 0.999) # one-sided p-value
  
      data.frame(
        scenario,
        n_total = nrow(df_enrolled),
        mean_pbo = mean(df_enrolled$value[df_enrolled$arm == "pbo"]),
        mean_trt = mean(df_enrolled$value[df_enrolled$arm == "trt"]),
        p_value = unname(logreg_p),
        stringsAsFactors = FALSE
      )
    }
  )
)
```

## Trial
Make multiple trial replicates.

```{r trial}
trials <- replicate_trial(
  trial_name = "test_trial",
  sample_size = sample_size,
  arms = arms,
  allocation = allocation,
  enrollment = enrollment_fn,
  dropout = dropout_fn,
  analysis_generators = analysis_generators,
  population_generators = population_generators,
  n = 3
)
```

## Simulate
To simulate all replicates:

```{r sim}
run_trials(trials)
```

Bind one row per replicate into one data frame.
```{r results}
replicate_results <- do.call(rbind, lapply(seq_along(trials), function(i) {
  data.frame(
    replicate = i,
    trials[[i]]$results[[1]]$final,
    stringsAsFactors = FALSE
  )
}))

replicate_results
```
