#' Replicate a Trial Object Multiple Times
#'
#' Creates \code{n} deep copies of an existing \code{Trial} R6 object.
#' Each replicated trial receives a modified name that appends the
#' replication index (e.g., "Trial 1", "Trial 2"). Both the \code{timer}
#' and all elements of the \code{population} field are cloned to ensure
#' independence between replicated trials.
#'
#' @param trial A \code{Trial} R6 object to be replicated. The object must
#'   include at least the fields \code{name}, \code{timer}, and
#'   \code{population}, and each of these fields must support the
#'   \code{$clone()} method.
#' @param n Integer specifying the number of replicated trials to create.
#'   Defaults to \code{1}.
#'
#' @return A list of \code{n} cloned \code{Trial} objects, each fully
#'   independent of the original and of each other.
#'
#' @examples
#' # Create 5 independent copies of a trial:
#' # replicated <- replicate_trial(trial, n = 5)
#'
#' @export
replicate_trial<- function(trial,n=1)
{
trials<-list()
for(i in 1:n){
temp<- Trial$new(
name = paste(trial$name, i),
timer = trial$timer$clone(),
population = lapply(trial$population,function(x){x$clone()}))
trials <- append(trials, temp)
}
return(trials)
}


#' Generate a Population Object from a Named Generator
#'
#' Helper to create a `Population` R6 object by running a provided generator function.
#'
#' @param name Character scalar; the population name (e.g., arm label).
#' @param generator A function with no required arguments that returns a data.frame-like object.
#'
#' @return A `Population` R6 object constructed as `Population$new(name = name, data = generator())`.
#'
#' @examples
#' gen_control <- function() data.frame(id = 1:5, value = rnorm(5))
#' pop <- gen_population(name = "control", generator = gen_control)
#'
#' @export
gen_population <-function(name=NULL,generator=NULL)
{
population<-Population$new(
name = name,
data = generator()
)
return(population)
}

#' Create Multiple Trials with Generated Populations
#'
#' Constructs \code{n} independent \code{Trial} objects using a common
#' trial name, a timer template, and a list of population‑generation
#' specifications. For each trial, a new name is created by appending
#' the trial index, the timer object is cloned, and the population is
#' generated by applying \code{gen_population()} to each element of
#' \code{data_gen_list}.
#'
#' @param trial_name Character string providing the base name for the
#'   generated trials. The index \code{i} is appended automatically.
#'   Defaults to \code{"name"}.
#'
#' @param data_gen_list A list where each element is a two‑element
#'   structure (e.g., list or vector) specifying the arguments passed to
#'   \code{gen_population()}. Each element must be indexable via
#'   \code{[[1]]} and \code{[[2]]}.
#'
#' @param timer A \code{timer} object supporting the \code{$clone()}
#'   method. A cloned timer is assigned to each generated trial.
#'
#' @param n Integer specifying the number of trials to create.
#'   Defaults to \code{1}.
#'
#' @return A list of \code{n} \code{Trial} objects, each with:
#'   \itemize{
#'     \item a unique name constructed from \code{trial_name} and the index,
#'     \item a cloned \code{timer},
#'     \item a population generated using \code{data_gen_list}.
#'   }
#' @export
create_multiple_trials_gen_pop<- function(trial_name='name',data_gen_list=NULL, timer=timer, n = 1)
{
trials <- list()
for (i in 1:n) {
# Create a cloned trial with updated name and cloned components
temp <- Trial$new(
name       = paste(trial_name, i),
timer      = timer$clone(),
population = lapply(data_gen_list, function(x) {gen_population(x[[1]],x[[2]]) })
)
trials <- append(trials, list(temp))
}
return(trials)
}
#' Run Multiple Trial Objects
#'
#' Applies the \code{$run()} method to each \code{Trial} object in a list.
#' This function is a convenience wrapper that executes a collection of
#' trials sequentially.
#'
#' @param trials A list of \code{Trial} R6 objects. Each object must
#'   implement a \code{$run()} method.
#'
#' @return A list containing the output returned by \code{$run()} for each
#'   trial. If \code{$run()} returns \code{NULL}, the result will be a list
#'   of \code{NULL} values.
#'
#' @examples
#' # Assuming `trials` is a list of Trial R6 objects:
#' # results <- run_multiple_trial(trials)
#'
#' @export


run_multiple_trial<-function(trials=NULL)
{
lapply(trials,function(x){ x$run()})
}


