#' Clone a Trial Object Multiple Times
#'
#' Creates \code{n} deep copies of an existing \code{Trial} R6 object.
#' Each replicated trial receives a modified name that appends the
#' replication index (e.g., "Trial 1", "Trial 2"). Both the \code{timer}
#' and all elements of the \code{population} field are cloned to ensure
#' independence between replicated trials.
#'
#' @param trial A \code{Trial} R6 object to be replicated. The object must
#'   include at least the fields \code{name}, \code{timer}, and
#'   \code{population}, and each of these fields must support the
#'   \code{$clone()} method.
#' @param n Integer specifying the number of replicated trials to create.
#'   Defaults to \code{1}.
#'
#' @return A list of \code{n} cloned \code{Trial} objects, each fully
#'   independent of the original and of each other.
#'
#' @examples
#' # Create 5 independent copies of a trial:
#' # replicated <- replicate_trial(trial, n = 5)
#'
#' @export
clone_trial <- function(trial, n = 1) {
  lapply(seq_len(n), function(i) {
    Trial$new(
      name = paste(trial$name, i, sep="_"),
      timer = trial$timer$clone(),
      population = lapply(trial$population, function(x) x$clone())
    )
  })
}

#' Generate a Population Object from a Named Generator
#'
#' Helper to create a `Population` R6 object by running a provided generator function.
#'
#' @param name Character scalar; the population name (e.g., arm label).
#' @param generator A function with no required arguments that returns a data.frame-like object.
#'
#' @return A `Population` R6 object constructed as `Population$new(name = name, data = generator())`.
#'
#' @examples
#' gen_control <- function() data.frame(id = 1:5, value = rnorm(5))
#' pop <- gen_population(name = "control", generator = gen_control)
#'
#' @export
gen_population <- function(name, generator, sample_size = 1) {
  Population$new(
    name = name,
    data = vector_to_dataframe(generator(sample_size))
  )
}

#' Create Multiple Trials with Generated Populations
#'
#' Constructs \code{n} independent \code{Trial} objects using a common
#' trial name, a timer template, and a list of population‑generation
#' specifications. For each trial, a new name is created by appending
#' the trial index, the timer object is cloned, and the population is
#' generated by applying \code{gen_population()} to each element of
#' \code{data_gen_list}.
#'
#' @param trial_name Character string providing the base name for the
#'   generated trials. The index \code{i} is appended automatically.
#'   Defaults to \code{"name"}.
#'
#' @param data_gen_list A list where each element is a two‑element
#'   structure (e.g., list or vector) specifying the arguments passed to
#'   \code{gen_population()}. Each element must be indexable via
#'   \code{[[1]]} and \code{[[2]]}.
#'
#' @param timer A \code{timer} object supporting the \code{$clone()}
#'   method. A cloned timer is assigned to each generated trial.
#'
#' @param n Integer specifying the number of trials to create.
#'   Defaults to \code{1}.
#'
#' @return A list of \code{n} \code{Trial} objects, each with:
#'   \itemize{
#'     \item a unique name constructed from \code{trial_name} and the index,
#'     \item a cloned \code{timer},
#'     \item a population generated using \code{data_gen_list}.
#'   }
#' @export
replicate_trial <- function(trial_name = "name", population_generators, plan_generator) {
  trial <- lapply(seq_len(n), function(i) {
    Trial$new(
      name = paste(trial_name, i, sep="_"),
      timer = Timer$new(name = paste("timer", i, sep="_")),
      population = lapply(names(population_generators), function(name) {
        gen_population(name, population_generators[[name]])
      })
    )
  })

  # TODO: for each trial generate a plan using the provided plan generator
}

#' Run Multiple Trial Objects
#'
#' Applies the \code{$run()} method to each \code{Trial} object in a list.
#' This function is a convenience wrapper that executes a collection of
#' trials sequentially.
#'
#' @param trials A list of \code{Trial} R6 objects. Each object must
#'   implement a \code{$run()} method.
#'
#' @return A list containing the output returned by \code{$run()} for each
#'   trial. If \code{$run()} returns \code{NULL}, the result will be a list
#'   of \code{NULL} values.
#'
#' @examples
#' # Assuming `trials` is a list of Trial R6 objects:
#' # results <- run_multiple_trial(trials)
#'
#' @export


run_trials <- function(trials) lapply(trials, function(trial) trial$run())
